<div>
	<h3><a href="about.html">about</a></h3>
	<img src="images/girl.jpg" alt="">
	<p>
		This is just a place holder, so you can see what the site would look like. This is just a place holder.<a href="about.html" class="more">(more)</a>
	</p>
</div>
<div>
	<h3><a href="blog.html">blog</a></h3>
	<p>
		This is just a place holder, so you can see what the site would look like. This is just a place holder.<a href="blog.html" class="more">(more)</a> <span>- Leah, Apr. 1 2012</span>
	</p>
</div>