<!DOCTYPE HTML>
<html>
<head>
	<meta charset="UTF-8">
	<title>MyBlog</title>
	<link rel="stylesheet" href="css/style.css" type="text/css">
</head>
<script type="text/javascript">
var FM = function(id,html){document.getElementById(id).innerHTML = document.getElementById(id).innerHTML+html;}
</script>
<body>
	<div id="page">
		<div id="header"></div>
		<div id="body"></div>
		<div id="footer"></div>
	</div>
</body>
</html>